services:
  auth_base:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      GDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres
    networks:
      - app-tier