spring:
  application:
    name: auth
  main:
    banner-mode: off

  profile:
    prod
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${AUTH_DATABASE_CONNECT}
    username: ${AUTH_DATABASE_USER}
    password: ${AUTH_DATABASE_PASSWORD}

  flyway:
    enable: true
    locations: classpath:migration
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8100

jwts:
  keys:
    private: ${JWT_KEY_PRIVATE}
    public: ${JWT_KEY_PUBLIC}
    public.lifetime: ${JWT_KEY_PRIVATE_LIFETIME}
    private.lifetime: ${JWT_KEY_PUBLIC_LIFETIME}

cors:
  allowedOrigins: ${CORS_ALLOWED_ORIGINS}