spring.application.name=auth

spring.profile=dev

spring.main.banner-mode=off
spring.output.ansi.enabled=ALWAYS

server.port=8100

spring.datasource.url=${AUTH_DATABASE_CONNECT}

spring.datasource.username=${AUTH_DATABASE_USER}
spring.datasource.password=${AUTH_DATABASE_PASSWORD}

jwts.keys.private=${JWT_KEY_PRIVATE}
jwts.keys.public=${JWT_KEY_PUBLIC}

jwts.keys.public.lifetime=${JWT_KEY_PRIVATE_LIFETIME}
jwts.keys.private.lifetime=${JWT_KEY_PUBLIC_LIFETIME}

cors.allowedOrigins=${CORS_ALLOWED_ORIGINS}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration